version: "3.9"

services:
  sonarr:
    image: docker.io/linuxserver/sonarr:version-3.0.10.1567@sha256:4f69472a0cdea29e23967db6a3395487539b759def3920327d1f49ae00b9dfd4
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config:/config
      - ${SONARR_DOWNLOADS_PATH}:/downloads:rw,rslave
      - ${SONARR_TV_PATH}:/tv:rw,rslave
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      - "traefik.http.routers.sonarr.service=sonarr"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - 'traefik.http.routers.sonarr.rule=Host("$SONARR_HOST")'
      - "traefik.http.routers.sonarr.middlewares=authelia@docker"
    networks:
      - web_proxy
      - torrent
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8989/login"]
      start_period: 20s
      interval: 30s
      timeout: 5s
      retries: 5

networks:
  web_proxy:
    external: true
  torrent:
    external: true
