version: "3.9"

services:
  prowlarr:
    image: docker.io/linuxserver/prowlarr:version-1.8.6.3946@sha256:8c5d3932109eed7d316d0b9e99285a71df86e85d7a1b9f72d70eb83de79475d1
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config:/config
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
      - "traefik.http.routers.prowlarr.service=prowlarr"
      - "traefik.http.routers.prowlarr.tls=true"
      - "traefik.http.routers.prowlarr.entrypoints=websecure"
      - 'traefik.http.routers.prowlarr.rule=Host("$PROWLARR_HOST")'
      - "traefik.http.routers.prowlarr.middlewares=authelia@docker"
    networks:
      - web_proxy
      - torrent
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:9696/login"]
      start_period: 20s
      interval: 30s
      timeout: 5s
      retries: 5

networks:
  web_proxy:
    external: true
  torrent:
    external: true
