version: "3.9"

services:
  maloja:
    image: docker.io/krateng/maloja:3.2.4@sha256:4ecea26058d2ca5168a8d53820279942d28f0606664cea6425f42371d5d88f95
    container_name: maloja
    #    user: ${PUID}:${PGID}
    environment:
      - MALOJA_DATA_DIRECTORY=/mljdata
      - MALOJA_FORCE_PASSWORD=${MALOJA_FORCE_PASSWORD}
    volumes:
      - ./data:/mljdata
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.maloja.loadbalancer.server.port=42010"
      - "traefik.http.routers.maloja.service=maloja"
      - "traefik.http.routers.maloja.tls=true"
      - "traefik.http.routers.maloja.entrypoints=websecure"
      - 'traefik.http.routers.maloja.rule=Host("$MALOJA_HOST")'
      - "traefik.http.routers.maloja.middlewares=authelia@docker"
    networks:
      - web_proxy
    # No healthcheck because no public endpoint

networks:
  web_proxy:
    external: true
