version: "3.9"

services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:8.5.0@sha256:5da14297a11aa910582d800f0edcb8f9e9d488642083c01dc34950f6449d9214
    container_name: recyclarr
    user: ${PUID}:${PGID}
    environment:
      - SONARR_API_KEY=${SONARR_API_KEY}
      - RADARR_API_KEY=${RADARR_API_KEY}
    volumes:
      - ./config:/config
    restart: unless-stopped
    networks:
      - torrent

networks:
  torrent:
    external: true
