version: "3.9"

services:
  homer:
    image: docker.io/b4bz/homer:v25.05.1@sha256:f861e8e7f456577d827c38a5d2bd72f5d2d2381e294b35f9c014d0cb2a97c7c7
    container_name: homer
    volumes:
      - ./assets:/www/assets
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.homer.loadbalancer.server.port=8080"
      - "traefik.http.routers.homer.service=homer"
      - "traefik.http.routers.homer.tls=true"
      - "traefik.http.routers.homer.entrypoints=websecure"
      - 'traefik.http.routers.homer.rule=Host("$HOMER_HOST")'
      - "traefik.http.routers.homer.middlewares=authelia@docker"
    networks:
      - web_proxy
    # No healthchek because already present in Dockerfile

networks:
  web_proxy:
    external: true
