version: "3.9"

services:
  homer:
    image: docker.io/b4bz/homer:v25.08.1@sha256:6231e77bb62047e0849bd67960076a90e79d00ab2f8eec3e2306b28d381a7c2e
    container_name: homer
    volumes:
      - ./assets:/www/assets
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.homer.loadbalancer.server.port=8080"
      - "traefik.http.routers.homer.service=homer"
      - "traefik.http.routers.homer.tls=true"
      - "traefik.http.routers.homer.entrypoints=websecure"
      - 'traefik.http.routers.homer.rule=Host("$HOMER_HOST")'
      - "traefik.http.routers.homer.middlewares=authelia@docker"
    networks:
      - web_proxy
    # No healthchek because already present in Dockerfile

networks:
  web_proxy:
    external: true
