{
 "title": "Traefik",
 "tags": [
  "main",
  "traefik",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(traefik_service_requests_total, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(traefik_entrypoint_open_connections, instance)"
   },
   {
    "name": "protocol",
    "label": "Protocol",
    "query": "label_values(traefik_service_requests_total, protocol)"
   },
   {
    "name": "entrypoint",
    "label": "Entrypoint",
    "query": "label_values(traefik_entrypoint_open_connections, entrypoint)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(traefik_service_requests_total{instance=~\"$instance\"}, service)"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum{job=\"$job\",protocol=~\"$protocol\",instance=~\"$instance\"}) / sum(traefik_service_requests_total{job=\"$job\",protocol=~\"$protocol\",instance=~\"$instance\"}) * 1000",
     "legendFormat": "Average response time"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{job=\"$job\",protocol=~\"$protocol\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "Requests 5min"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(traefik_service_open_connections{job=\"$job\",protocol=~\"$protocol\",instance=~\"$instance\"})",
     "legendFormat": "Open connections"
    }
   ]
  },
  {
   "title": "Requests over 5min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (increase(traefik_service_requests_total{job=\"$job\",protocol=~\"$protocol\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Requests by service",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 5 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total[5m])) by (service) ",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Average response time by service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum{job=~\"$job\",protocol=~\"$protocol\",instance=~\"$instance\"}) by (service) / sum(traefik_service_request_duration_seconds_count{job=~\"$job\",protocol=~\"$protocol\",instance=~\"$instance\"}) by (service)",
     "legendFormat": " {{service}}"
    }
   ]
  },
  {
   "title": "Requests by return code",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (code) (traefik_service_requests_total{job=\"$job\",protocol=~\"$protocol\",instance=~\"$instance\"})",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Requests by method",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 14 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (method) (traefik_service_requests_total{job=\"$job\",protocol=~\"$protocol\",instance=~\"$instance\"})",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Requests by protocol",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 14 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (protocol) (traefik_service_requests_total{job=\"$job\",protocol=~\"$protocol\",instance=~\"$instance\"})",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Requests by instance",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 14 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (instance) (traefik_service_requests_total{job=\"$job\",protocol=~\"$protocol\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "$service stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum{job=\"$job\",service=\"$service\",protocol=~\"$protocol\",instance=~\"$instance\"}) / sum(traefik_service_requests_total{job=\"$job\",service=\"$service\",protocol=~\"$protocol\",instance=~\"$instance\"}) * 1000",
     "legendFormat": "Response time"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "traefik_service_request_duration_seconds_sum{job=\"$job\",service=\"$service\",protocol=~\"$protocol\",instance=~\"$instance\"} / traefik_service_requests_total{job=\"$job\",service=\"$service\",protocol=~\"$protocol\",instance=~\"$instance\"} * 1000",
     "legendFormat": "{{method}} ({{protocol}}): {{code}}"
    }
   ]
  },
  {
   "title": "Requests over 5min",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(traefik_service_requests_total{job=\"$job\",service=\"$service\",protocol=~\"$protocol\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{method}} ({{protocol}}): {{code}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{job=\"$job\",service=\"$service\",protocol=~\"$protocol\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "Requests 5min"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 31 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "traefik_service_requests_total{job=\"$job\",service=\"$service\",protocol=~\"$protocol\",instance=~\"$instance\"}",
     "legendFormat": "{{method}} ({{protocol}}): {{code}}"
    }
   ]
  },
  {
   "title": "Requests by return code",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 7, "y": 31 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (code) (traefik_service_requests_total{job=\"$job\",service=\"$service\",protocol=~\"$protocol\",instance=~\"$instance\"})",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Requests by method",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 13, "y": 31 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (method) (traefik_service_requests_total{job=\"$job\",service=\"$service\",protocol=~\"$protocol\",instance=~\"$instance\"})",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Requests by protocol",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 31 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (protocol) (traefik_service_requests_total{job=\"$job\",service=\"$service\",protocol=~\"$protocol\",instance=~\"$instance\"})",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  { "type": "mxswat-separator-panel", "gridPos": { "h": 5, "w": 24, "x": 0, "y": 38 } }
 ]
}