version: "3.9"

services:
  syncthing:
    image: docker.io/linuxserver/syncthing:2.0.2@sha256:210b3d07daaa68c5c496ddb2848ea0e8677c840b6acd234099d54e67cf0733c4
    container_name: syncthing
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config:/config
      - ${SYNCTHING_DATA_PATH}:/mnt/syncthing
    ports:
      - ${SYNCTHING_PORT}:22000
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.syncthing.loadbalancer.server.port=8384"
      - "traefik.http.routers.syncthing.service=syncthing"
      - "traefik.http.routers.syncthing.tls=true"
      - "traefik.http.routers.syncthing.entrypoints=websecure"
      - 'traefik.http.routers.syncthing.rule=Host("$SYNCTHING_HOST")'
      - "traefik.http.routers.syncthing.middlewares=authelia@docker"
    networks:
      - web_proxy
    # No healthcheck because no public endpoint

networks:
  web_proxy:
    external: true
