version: "3.9"

services:
  syncthing:
    image: docker.io/linuxserver/syncthing:2.0.12@sha256:b2dbc42f95154986ae3578256f3fa9612fa7e930184d823aa56192b478fa0b8a
    container_name: syncthing
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config:/config
      - ${SYNCTHING_DATA_PATH}:/mnt/syncthing
    ports:
      - ${SYNCTHING_PORT}:22000
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.syncthing.loadbalancer.server.port=8384"
      - "traefik.http.routers.syncthing.service=syncthing"
      - "traefik.http.routers.syncthing.tls=true"
      - "traefik.http.routers.syncthing.entrypoints=websecure"
      - 'traefik.http.routers.syncthing.rule=Host("$SYNCTHING_HOST")'
      - "traefik.http.routers.syncthing.middlewares=authelia@docker"
    networks:
      - web_proxy
    # No healthcheck because no public endpoint

networks:
  web_proxy:
    external: true
