{
 "title": "UptimeRobot",
 "tags": [
  "main",
  "uptimerobot",
  "uptimerobot_exporter",
  "prometheus"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(uptimerobot_monitor_status, job)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(uptimerobot_monitor_status{job=\"$job\"}, name)"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptimerobot_up{job=~\"$job\"}",
     "legendFormat": "Exporter status"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptimerobot_monitor_status{job=~\"$job\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptimerobot_scrape_duration_milliseconds{job=~\"$job\"}",
     "legendFormat": "Scrape duration"
    }
   ]
  },
  {
   "title": "Monitors Response time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "uptimerobot_monitor_response_time_millisecond{job=~\"$job\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  { "title": "$service stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptimerobot_monitor_status{job=~\"$job\",name=\"$service\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "uptimerobot_monitor_response_time_millisecond{job=~\"$job\",name=\"$service\"}",
     "legendFormat": "Average response time"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptimerobot_monitor_log_type{job=~\"$job\",name=\"$service\"}",
     "legendFormat": "Last log"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptimerobot_monitor_log_datetime{job=~\"$job\",name=\"$service\"}*1000",
     "legendFormat": "Las log start"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - uptimerobot_monitor_log_datetime{job=~\"$job\",name=\"$service\"}",
     "legendFormat": "Last log duration"
    }
   ]
  },
  {
   "title": "Monitor Response time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "uptimerobot_monitor_response_time_millisecond{job=~\"$job\",name=\"$service\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Monitor Status",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "uptimerobot_monitor_status{job=~\"$job\",name=\"$service\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}