version: "3.9"

services:
  jellyseerr:
    image: docker.io/fallenbagel/jellyseerr:2.2.2@sha256:fe72f4b341fa5c3275826a39aebfff23cbd552c956b0ab2d51dfba6a49b528f8
    container_name: jellyseerr
    volumes:
      - ./config:/app/config
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.jellyseerr.loadbalancer.server.port=5055"
      - "traefik.http.routers.jellyseerr.service=jellyseerr"
      - "traefik.http.routers.jellyseerr.tls=true"
      - "traefik.http.routers.jellyseerr.entrypoints=websecure"
      - 'traefik.http.routers.jellyseerr.rule=Host("$JELLYSEERR_HOST")'
    # - "traefik.http.routers.jellyseerr.middlewares=authelia@docker"
    networks:
      - web_proxy
      - torrent
    healthcheck:
      test: ["CMD", "wget", "-q", "--no-verbose", "--tries", "1", "--spider", "--timeout", "2", "http://localhost:5055/api/v1/status"]
      start_period: 20s
      interval: 30s
      timeout: 5s
      retries: 5

networks:
  web_proxy:
    external: true
  torrent:
    external: true
